{% set name = "opentelemetry-api" %}
{% set version = "1.23.0" %}
{% set sha256 = "14a766548c8dd2eb4dfc349739eb4c3893712a0daa996e5dbf945f9da665da9d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_api-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - deprecated >=1.2.6
    - aiocontextvars  # [py<37]
    - importlib-metadata >=6.0,<7.0
    - python

test:
  imports:
    - opentelemetry
    - opentelemetry.context
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenTelemetry Python / API
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/opentelemetry-api
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://opentelemetry-python.readthedocs.io/en/latest/
  doc_source_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/docs
  description: |-
    OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source
    Observability framework for instrumenting, generating, collecting, and exporting
    telemetry data such as traces, metrics, logs. As an industry-standard
    it is natively supported by a number of vendors.

extra:
  recipe-maintainers:
    - mariusvniekerk
    - marcelotrevisani
