{% set name = "opentelemetry-api" %}
{% set version = "1.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 79ab791b4aaad27acc3dc3ba01596db5b5aac2ef75c70622c6038051d6c2cded

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - deprecated >=1.2.6
    - setuptools >=16.0,<82

test:
  imports:
    - opentelemetry
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenTelemetry Python / API
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/opentelemetry-api
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://opentelemetry-python.readthedocs.io/en/latest/
  doc_source_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/docs
  description: |-
    OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source
    Observability framework for instrumenting, generating, collecting, and exporting
    telemetry data such as traces, metrics, logs. As an industry-standard
    it is natively supported by a number of vendors

extra:
  recipe-maintainers:
    - mariusvniekerk
    - marcelotrevisani
